# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 77999453+mzf11125@users.noreply.github.com
author_name: M Zidan Fatonie
contract_name: session
deployment_language: python
preset_name: starter
project_name: session1-contracts

